package lexer.token;

public enum TokenType {
    INT, BOOL, STRING, FILE, CATALOGUE, DATE,
    ASSIGN_OP,
    RELATIONAL_OP,
    ARITHMETIC_OP,
    LOGICAL_OP,
    IF, ELSE, FOREACH,
    CONST_INT, CONST_STRING, CONST_DATE, CONST_BOOL,
    IDENTIFIER,
    COMMA, PERIOD, SEMICOLON, COLON,
    RETURN,
    OPEN_BRACE, CLOSED_BRACE, OPEN_CURLY_BRACE, CLOSED_CURLY_BRACE, OPEN_SQUARE_BRACE, CLOSED_SQUARE_BRACE,
    EMPTY
}
